[package]
name = "capia-project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
capia-time.workspace = true
capia-model.workspace = true
capia-commands.workspace = true
capia-store.workspace = true
capia-assets.workspace = true
capia-media.workspace = true
serde.workspace = true
serde_json.workspace = true
